<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="XSD">
      <schema location="../xsd/HL7/ADT_A01.xsd"/>
      <rootElement name="ADT_A01" namespace="urn:oracle:integration:b2b:F6584ABE381B43298151720795E2910B"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="XSD">
      <schema location="../xsd/HL7/FIAB_IN010001UV01.xsd"/>
      <rootElement name="FIAB_IN010001UV01" namespace="urn:hl7-org:v3"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.2.0(build 091103.1205.1216) AT [WED JAN 26 20:42:14 EST 2011]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:xpath20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:ns0="urn:oracle:integration:b2b:F6584ABE381B43298151720795E2910B"
                xmlns:mf="http://www.oracle.com/XSL/Transform/java/com.oracle.reusable.asset.FormatName"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:ns1="urn:hl7-org:v3"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:geo="http://www.oracle.com/XSL/Transform/java/com.oracle.reusable.asset.HelloWorldXSLTest"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:mif="urn:hl7-org:v3/mif"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl ns0 xsd ns1 mif xpath20 bpws mhdr oraext dvm mf hwf med geo ids xdk xref ora socket ldap">
  <xsl:template match="/">
    <ns1:FIAB_IN010001UV01>
      <ns1:processingCode>
        <xsl:attribute name="code">
          <xsl:value-of select='oraext:left-trim(concat(/ns0:ADT_A01/ns0:MSH/@Type,"PatientName"))'/>
        </xsl:attribute>
      </ns1:processingCode>
    </ns1:FIAB_IN010001UV01>
  </xsl:template>
</xsl:stylesheet>
